### ISSUE TITLE
PeraPera language class

### ISSUE THREAD

**Issue by Gaitz** [Gaitz/Note#66]
## Pera Pera language class and flow issue or improvement
Search for classes
- 熱門 - 教練課程 在個別語言課程之上，在使用選單 filter 時無法第一時間知道是否開始搜尋與取得搜尋結果。需要手動下拉才知道。
- 學習目標選單, 在多選後取消有 bug 沒有正常取消，會一直產生

UI
- 頁面 UI 有很大的進步空間，過於陽春
- Logout 後重新登入的 UI 有點慘
![image](https://user-images.githubusercontent.com/5541565/118435890-65ca8e80-b712-11eb-8c35-66484587543d.png)

Register
- Gmail 註冊信被歸類在垃圾信件中
- ~~用途不明的空白輸入框~~ (Tom fixed)
![image](https://user-images.githubusercontent.com/5541565/118434958-88f43e80-b710-11eb-9d32-f59b50a9d434.png)
- 需要更動態的註冊信內容
![image](https://user-images.githubusercontent.com/5541565/118435729-15ebc780-b712-11eb-877f-3ff4ec4dbba9.png)
- Line 與 email 信箱連結的說明與連結方式,  應該更自動化, (等待時間更短, 更容易操作)

試用課程
- 課程教材清單, 預設的縮小狀態看起來像破版 
![image](https://user-images.githubusercontent.com/5541565/118923053-8f332680-b96d-11eb-8051-6a451c41077c.png)
- Line 課程, 在 in app browser 開啟, 速度有點慢 
- Line 課程, 課程學習，習慣在電腦版 (PC) 開啟, 希望有個機制可以方便在電腦版開啟對應的課程
    - 在不需要安裝 Line PC 版 App 取得連結的情況下，可以考慮發送 email 帶有課程連結, ...
    - 或者從 perapera 網站進去可以找到訂閱的課程內容
- Fixed ~~日文試讀課程, 試讀第三天－老師詳細解說，裡面提到的新的內容並沒有影片呈現，找不到學習資源~~

**Comment by tomsnorkel** [comment]
有部份Bug 想在這裏回應一下: 
-  我己經作簡單的修正，並且想一下如何避免再有類似的情況。(如使用更動態的Variable) 
-  Line 目前與電郵的連結需要由人手操作，故此會出現時間差的情況，未來其實是必需要自動化。
-  現時我們使用Line 課程的連結是 liff 連結，其特性是: 
    - 如果在App 中開啟其連結會是相對應的課程。
    - 在Desktop 開啟則是正常的課程。
